name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        working-directory: ./storefront
        run: npm ci
      
      - name: Run ESLint
        working-directory: ./storefront
        run: npm run lint
      
      - name: Run Jest tests
        working-directory: ./storefront
        run: npm test
      
      - name: Generate coverage report
        working-directory: ./storefront
        run: npm run test:coverage
name: Run Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
      continue-on-error: true
    
    - name: Run Jest tests
      run: npm test
      continue-on-error: true
    
    - name: Generate coverage report
      run: npm run test:coverage
      continue-on-error: true
    
    - name: Upload coverage to Codecov (optional)
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      with:
        file: ./coverage/coverage-final.json
        fail_ci_if_error: false
